/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PecaController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rmb
 */
public class MenuCaixaView extends javax.swing.JFrame {

    /**
     * Creates new form MenuClientesView
     */
    public MenuCaixaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRelatorioMensal = new javax.swing.JButton();
        ButtonContabilizarEstoque = new javax.swing.JButton();
        ButtonVendasdoDia = new javax.swing.JButton();
        buttonRelatorioAnual = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGO - Menu Clientes");
        setBackground(new java.awt.Color(74, 216, 236));
        setMinimumSize(new java.awt.Dimension(1000, 548));
        setResizable(false);

        buttonRelatorioMensal.setBackground(new java.awt.Color(0, 204, 204));
        buttonRelatorioMensal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buttonRelatorioMensal.setForeground(new java.awt.Color(255, 255, 255));
        buttonRelatorioMensal.setText("Relatório mensal");
        buttonRelatorioMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatorioMensalActionPerformed(evt);
            }
        });

        ButtonContabilizarEstoque.setBackground(new java.awt.Color(0, 204, 204));
        ButtonContabilizarEstoque.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ButtonContabilizarEstoque.setForeground(new java.awt.Color(255, 255, 255));
        ButtonContabilizarEstoque.setText("Contabilizar \nEstoque");
        ButtonContabilizarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonContabilizarEstoqueActionPerformed(evt);
            }
        });

        ButtonVendasdoDia.setBackground(new java.awt.Color(0, 204, 204));
        ButtonVendasdoDia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ButtonVendasdoDia.setForeground(new java.awt.Color(255, 255, 255));
        ButtonVendasdoDia.setText("Vendas do dia");
        ButtonVendasdoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVendasdoDiaActionPerformed(evt);
            }
        });

        buttonRelatorioAnual.setBackground(new java.awt.Color(0, 204, 204));
        buttonRelatorioAnual.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buttonRelatorioAnual.setForeground(new java.awt.Color(255, 255, 255));
        buttonRelatorioAnual.setText("Relatório anual");
        buttonRelatorioAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatorioAnualActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Trocar senha");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(ButtonVendasdoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(690, 690, 690)
                .addComponent(ButtonContabilizarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(511, 511, 511)
                .addComponent(buttonRelatorioAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(buttonRelatorioMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(840, 840, 840)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(ButtonVendasdoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(ButtonContabilizarEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(buttonRelatorioAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(buttonRelatorioMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        new MenuPrincipal().setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonVendasdoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVendasdoDiaActionPerformed

        try {
            new TelaExibirVendas().setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(MenuCaixaView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuCaixaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ButtonVendasdoDiaActionPerformed

    private void buttonRelatorioMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatorioMensalActionPerformed

        new TelaRelatorioMensal().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonRelatorioMensalActionPerformed

    private void ButtonContabilizarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonContabilizarEstoqueActionPerformed
        try {
            PecaController pecaController = new PecaController();
            String mensagem = pecaController.contabilizarProdutos();
            JOptionPane.showMessageDialog(null, mensagem);
        } catch (IOException ex) {
            Logger.getLogger(MenuCaixaView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuCaixaView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ButtonContabilizarEstoqueActionPerformed

    private void buttonRelatorioAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatorioAnualActionPerformed
       
        new TelaRelatorioAnual().setVisible(true);
        dispose();

    }//GEN-LAST:event_buttonRelatorioAnualActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        new TelaTrocarSenha().setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCaixaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCaixaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonContabilizarEstoque;
    private javax.swing.JButton ButtonVendasdoDia;
    private javax.swing.JButton buttonRelatorioAnual;
    private javax.swing.JButton buttonRelatorioMensal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
