/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PecaController;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Peca;

/**
 *
 * @author rmb
 */
public class TelaBuscarPeca extends javax.swing.JFrame {
    
    private final DefaultTableModel tabelaPecas;
    private PecaController controller;
    /**
     * Creates new form TelaBuscarPeca
     */
    public TelaBuscarPeca() {
        initComponents();
        tabelaPecas = (DefaultTableModel) jtPeca.getModel();
        try {
            controller = new PecaController();
            int tamanho = tabelaPecas.getRowCount();
            for (int i=0; i<tamanho; i++) {
                tabelaPecas.removeRow(0);
            }

            ArrayList<Peca> pecas = controller.getPecas();
            if(pecas != null){
                for (Peca peca : pecas) {
                    Object[] dados = {peca.getNome(), peca.getQuantidade(), peca.getPrecoCusto(), peca.getPrecoVenda(), peca.getPrateleira(), peca.getLocal()};
                    tabelaPecas.addRow(dados);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaBuscarPeca.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaBuscarPeca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPeca = new javax.swing.JTable();
        buttonVoltar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        buttonAdicionar = new javax.swing.JButton();
        buttonCadastrar = new javax.swing.JButton();
        buttonSemEstoque = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGO - Buscar peça");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar");

        tfNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeKeyReleased(evt);
            }
        });

        jtPeca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtPeca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade", "Custo (R$)", "Venda (R$)", "Prateleira", "Local"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtPeca);
        if (jtPeca.getColumnModel().getColumnCount() > 0) {
            jtPeca.getColumnModel().getColumn(0).setMinWidth(200);
            jtPeca.getColumnModel().getColumn(1).setResizable(false);
            jtPeca.getColumnModel().getColumn(2).setResizable(false);
            jtPeca.getColumnModel().getColumn(3).setResizable(false);
            jtPeca.getColumnModel().getColumn(4).setResizable(false);
            jtPeca.getColumnModel().getColumn(5).setResizable(false);
        }

        buttonVoltar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        buttonEditar.setBackground(new java.awt.Color(0, 204, 204));
        buttonEditar.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonEditar.setForeground(new java.awt.Color(254, 254, 254));
        buttonEditar.setText("Editar");
        buttonEditar.setPreferredSize(new java.awt.Dimension(101, 29));
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonRemover.setBackground(new java.awt.Color(0, 204, 204));
        buttonRemover.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonRemover.setForeground(new java.awt.Color(254, 254, 254));
        buttonRemover.setText("Excluir");
        buttonRemover.setPreferredSize(new java.awt.Dimension(101, 29));
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        buttonAdicionar.setBackground(new java.awt.Color(0, 204, 204));
        buttonAdicionar.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonAdicionar.setForeground(new java.awt.Color(254, 254, 254));
        buttonAdicionar.setText("Ad. Estoque");
        buttonAdicionar.setPreferredSize(new java.awt.Dimension(101, 29));
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        buttonCadastrar.setBackground(new java.awt.Color(0, 204, 204));
        buttonCadastrar.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonCadastrar.setForeground(new java.awt.Color(254, 254, 254));
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        buttonSemEstoque.setBackground(new java.awt.Color(0, 204, 204));
        buttonSemEstoque.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        buttonSemEstoque.setForeground(new java.awt.Color(255, 255, 255));
        buttonSemEstoque.setText("Sem estoque");
        buttonSemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSemEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSemEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 143, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSemEstoque)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCadastrar))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        
        new MenuPrincipal().setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void tfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyPressed
        
        int tamanho = tabelaPecas.getRowCount();
        for (int i=0; i<tamanho; i++) {
            tabelaPecas.removeRow(0);
        }
        String nome = tfNome.getText().toLowerCase();
        ArrayList<Peca> pecas = controller.buscarPorNome(nome);
        if(pecas != null){
            for (Peca peca : pecas) {
                Object[] dados = {peca.getNome(), peca.getQuantidade(), peca.getPrecoCusto(), peca.getPrecoVenda(), peca.getPrateleira(), peca.getLocal()};
                tabelaPecas.addRow(dados);
            }
        }
        
    }//GEN-LAST:event_tfNomeKeyPressed

    private void tfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyReleased
        
        int tamanho = tabelaPecas.getRowCount();
        for (int i=0; i<tamanho; i++) {
            tabelaPecas.removeRow(0);
            
        }
        String nome = tfNome.getText().toLowerCase();
        ArrayList<Peca> pecas = controller.buscarPorNome(nome);
        if(pecas != null){
            for (Peca peca : pecas) {
                Object[] dados = {peca.getNome(), peca.getQuantidade(), peca.getPrecoCusto(), peca.getPrecoVenda(), peca.getPrateleira(), peca.getLocal()};
                tabelaPecas.addRow(dados);
            }
        }

    }//GEN-LAST:event_tfNomeKeyReleased

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        int linha = jtPeca.getSelectedRow();
        if(linha != -1) {
            String nome = tabelaPecas.getValueAt(linha, 0).toString();
            if(JOptionPane.showConfirmDialog(null, "Deseja realmente excluir " + nome) == JOptionPane.YES_NO_OPTION){
                try {
                    controller.removerPeca(nome);
                    tabelaPecas.removeRow(linha);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaBuscarPeca.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TelaBuscarPeca.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha antes de excluir");
        }
        
    }//GEN-LAST:event_buttonRemoverActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed

        int linha = jtPeca.getSelectedRow();
        if(linha != -1) {
            String nome = tabelaPecas.getValueAt(linha, 0).toString();
            String quantidade = tabelaPecas.getValueAt(linha, 1).toString();
            String custo = tabelaPecas.getValueAt(linha, 2).toString();
            String venda = tabelaPecas.getValueAt(linha, 3).toString();
            String prateleira = tabelaPecas.getValueAt(linha, 4).toString();
            String local = tabelaPecas.getValueAt(linha, 5).toString();
            new TelaEditarPeca(nome, quantidade, custo, venda, prateleira, local).setVisible(true);
            dispose();
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha antes de editar");
        }
        
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarActionPerformed
        
        int linha = jtPeca.getSelectedRow();
        if(linha != -1) {
            String nome = tabelaPecas.getValueAt(linha, 0).toString();
            new TelaAdicionarEstoque(nome).setVisible(true);
            dispose();
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha antes de adicionar estoque");
        }

    }//GEN-LAST:event_buttonAdicionarActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed

        new TelaCadastroPeca().setVisible(true);
        dispose();

    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void buttonSemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSemEstoqueActionPerformed
        int tamanho = tabelaPecas.getRowCount();
        for (int i=0; i<tamanho; i++) {
            tabelaPecas.removeRow(0);
        }
        
        if(buttonSemEstoque.isSelected()){

            ArrayList<Peca> pecas = controller.getSemEstoque();
            if(pecas != null){
                for (Peca peca : pecas) {
                    Object[] dados = {peca.getNome(), peca.getQuantidade(), peca.getPrecoCusto(), peca.getPrecoVenda(), peca.getPrateleira(), peca.getLocal()};
                    tabelaPecas.addRow(dados);
                }
            }
        }
        else{
            
            ArrayList<Peca> pecas = controller.getPecas();
            if(pecas != null){
                for (Peca peca : pecas) {
                    Object[] dados = {peca.getNome(), peca.getQuantidade(), peca.getPrecoCusto(), peca.getPrecoVenda(), peca.getPrateleira(), peca.getLocal()};
                    tabelaPecas.addRow(dados);
                }
            }
        }

    }//GEN-LAST:event_buttonSemEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscarPeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscarPeca().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JToggleButton buttonSemEstoque;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtPeca;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
