/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CadernetaController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Caderneta;

/**
 *
 * @author rmb
 */
public class TelaRecebimento extends javax.swing.JFrame {

    /**
     * Creates new form TelaRecebimento
     */
    Caderneta caderneta;
    public TelaRecebimento(Caderneta caderneta) {
        initComponents();
        this.caderneta = caderneta;
        jlTotal.setText(String.format("%.2f", caderneta.getValorTotal()));
        jlPago.setText(String.format("%.2f", caderneta.getValorPago()));
        jlRestante.setText(String.format("%.2f", caderneta.getValorDevedor()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfRecebimento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jlPago = new javax.swing.JLabel();
        jlRestante = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfData = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGO - Recebimento");
        setResizable(false);

        buttonVoltar.setBackground(new java.awt.Color(203, 203, 203));
        buttonVoltar.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setText("Recebimento (R$):");

        tfRecebimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfRecebimentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfRecebimentoKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setText("Valor total (R$):");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setText("Valor pago (R$):");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setText("Valor restante (R$):");

        jlTotal.setText("0");

        jlPago.setText("0");

        jlRestante.setText("0");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setText("Próxima data:");

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPago))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlRestante))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonVoltar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlPago))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlRestante))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        try {
            new TelaExibirCadernetas().setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(TelaRecebimento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaRecebimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void tfRecebimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRecebimentoKeyPressed
        String tfPagamento = tfRecebimento.getText();
        
        if(!tfPagamento.equals("")){
            float pagamento = Float.parseFloat(tfPagamento);
            float restante = caderneta.getValorDevedor();
            float result = restante - pagamento;
            if(result >= 0){
                jlRestante.setText(String.format("%.2f", result));
                if(result == 0){
                    tfData.setEnabled(false);
                }
                else{
                    tfData.setEnabled(true);
                }
            }
            else{
                jlRestante.setText("0");
            }
        }
        else{
            jlRestante.setText(String.format("%.2f", caderneta.getValorDevedor()));
        }

    }//GEN-LAST:event_tfRecebimentoKeyPressed

    private void tfRecebimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRecebimentoKeyReleased
        String tfPagamento = tfRecebimento.getText().replace(",", ".");
        
        if(!tfPagamento.equals("")){
            float pagamento = Float.parseFloat(tfPagamento);
            float restante = caderneta.getValorDevedor();
            float result = restante - pagamento;
            if(result >= 0){
                jlRestante.setText(String.format("%.2f", result));
                if(result == 0){
                    tfData.setEnabled(false);
                }
                else{
                    tfData.setEnabled(true);
                }
            }
            else{
                jlRestante.setText("0");
            }
        }
        else{
            jlRestante.setText(String.format("%.2f", caderneta.getValorDevedor()));
        }


    }//GEN-LAST:event_tfRecebimentoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tfPagamento = tfRecebimento.getText().replace(",", ".");
        if(!tfPagamento.equals("")){
            if(!tfPagamento.matches("[a-zA-Z]*") && !tfPagamento.matches("[!@#$%*()_+=-]*")){
                tfPagamento = tfPagamento.replace(",", ".");
                float recebimento = Float.parseFloat(tfPagamento);
                String cpf = caderneta.getCliente().getCpf();
                String data = caderneta.getDataAbertura();
                String dataPagamento = tfData.getText();
                float resto = Float.parseFloat(jlRestante.getText().replace(",", "."));
                try {
                    CadernetaController cadernetaController = new CadernetaController();
                    if(cadernetaController.receberPagamento(cpf, data, recebimento, resto, dataPagamento)){
                        JOptionPane.showMessageDialog(null, "Pagamento recebido");
                        dispose();
                        new TelaExibirCadernetas().setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Erro ao receber pagamento");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(TelaRecebimento.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaRecebimento.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Digite somente números no campo de recebimento. Ex: 99,99");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "O recebimento não pode ser vazio");
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jlPago;
    private javax.swing.JLabel jlRestante;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfRecebimento;
    // End of variables declaration//GEN-END:variables
}
