/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import models.Caderneta;
import models.Cliente;
import models.Venda;
import models.Peca;
import models.Servico;

/**
 *
 * @author rmb
 */
public class TelaDetalhesCaderneta extends javax.swing.JFrame {

    /**
     * Creates new form TelaDetalhesProduto
     */
    public TelaDetalhesCaderneta(Caderneta caderneta) {
        initComponents();
        
        Cliente cliente = caderneta.getCliente();
        jlNome.setText(cliente.getNome());
        jlCpf.setText(cliente.getCpf());
        jlEmail.setText(cliente.getEmail());
        jlTelefone.setText(cliente.getTelefone());
        
        Venda venda = caderneta.getVenda();
        String produtos = "";
        int cont = 0;
        ArrayList<Integer> quantidade = venda.getQuantidades();
        for(Peca peca : venda.getProdutos()){
            produtos = peca.getNome() + " (" + quantidade.get(cont) + ")" + "\n";
            taProdutos.append(produtos);
            cont++;
        }
        
        String os = "";
        for(Servico servico : venda.getServico()){
            os = servico.getServico() + "\n";
            taServicos.append(os);
        }
        
        jlTotal.setText(String.format("%.2f", caderneta.getValorTotal()));
        jlPago.setText(String.format("%.2f", caderneta.getValorPago()));
        jlRestante.setText(String.format("%.2f", caderneta.getValorDevedor()));
        
        jlAbertura.setText(caderneta.getDataAbertura());
        jlPagamento.setText(caderneta.getDataPagamento());
        jlFechamento.setText(caderneta.getDataFechamento());
        jlStatus.setText(caderneta.getStatus());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        buttonVoltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlPago = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlRestante = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlAbertura = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlPagamento = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlFechamento = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        taProdutos = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taServicos = new javax.swing.JTextArea();
        jlStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGO - Detalhes Produto");
        setMinimumSize(new java.awt.Dimension(470, 640));
        setResizable(false);
        setSize(new java.awt.Dimension(611, 740));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 114, 48, 18);

        jlNome.setForeground(new java.awt.Color(255, 255, 255));
        jlNome.setText("nome");
        getContentPane().add(jlNome);
        jlNome.setBounds(10, 140, 40, 18);

        buttonVoltar.setBackground(new java.awt.Color(203, 203, 203));
        buttonVoltar.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonVoltar);
        buttonVoltar.setBounds(10, 11, 100, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Informações cliente");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(174, 60, 210, 18);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 114, 32, 18);

        jlCpf.setForeground(new java.awt.Color(255, 255, 255));
        jlCpf.setText("12345678942");
        getContentPane().add(jlCpf);
        jlCpf.setBounds(320, 140, 88, 18);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-mail");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 172, 50, 18);

        jlEmail.setForeground(new java.awt.Color(255, 255, 255));
        jlEmail.setText("email");
        getContentPane().add(jlEmail);
        jlEmail.setBounds(10, 198, 37, 18);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefone");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 172, 71, 18);

        jlTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jlTelefone.setText("3599999999");
        getContentPane().add(jlTelefone);
        jlTelefone.setBounds(320, 198, 80, 18);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Informações compra");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 236, 143, 18);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Produtos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 268, 74, 18);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 268, 24, 18);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Valor Total (R$)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 395, 129, 18);

        jlTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlTotal.setText("999");
        getContentPane().add(jlTotal);
        jlTotal.setBounds(10, 421, 60, 18);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Valor Pago (R$)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 453, 129, 18);

        jlPago.setForeground(new java.awt.Color(255, 255, 255));
        jlPago.setText("999");
        getContentPane().add(jlPago);
        jlPago.setBounds(10, 479, 60, 18);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Valor Restante (R$)");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 511, 162, 18);

        jlRestante.setForeground(new java.awt.Color(255, 255, 255));
        jlRestante.setText("999");
        getContentPane().add(jlRestante);
        jlRestante.setBounds(10, 537, 70, 18);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Data de abertura");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(242, 395, 140, 18);

        jlAbertura.setForeground(new java.awt.Color(255, 255, 255));
        jlAbertura.setText("01/01/1990");
        getContentPane().add(jlAbertura);
        jlAbertura.setBounds(242, 421, 150, 18);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data de pagamento");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(242, 453, 162, 18);

        jlPagamento.setForeground(new java.awt.Color(255, 255, 255));
        jlPagamento.setText("01/01/1990");
        getContentPane().add(jlPagamento);
        jlPagamento.setBounds(242, 479, 140, 18);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Data de fechamento");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(242, 511, 168, 18);

        jlFechamento.setForeground(new java.awt.Color(255, 255, 255));
        jlFechamento.setText("01/01/1990");
        getContentPane().add(jlFechamento);
        jlFechamento.setBounds(242, 537, 150, 18);

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Status");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 569, 54, 18);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 220, 458, 10);

        taProdutos.setEditable(false);
        taProdutos.setBackground(new java.awt.Color(102, 102, 102));
        taProdutos.setColumns(20);
        taProdutos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        taProdutos.setForeground(new java.awt.Color(255, 255, 255));
        taProdutos.setRows(5);
        jScrollPane2.setViewportView(taProdutos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 293, 210, 87);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 720));

        taServicos.setEditable(false);
        taServicos.setBackground(new java.awt.Color(102, 102, 102));
        taServicos.setColumns(20);
        taServicos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        taServicos.setForeground(new java.awt.Color(255, 255, 255));
        taServicos.setRows(5);
        jScrollPane1.setViewportView(taServicos);

        jlStatus.setForeground(new java.awt.Color(255, 255, 255));
        jlStatus.setText("aberto/fechado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jlStatus)
                .addGap(94, 94, 94))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed

        dispose();

    }//GEN-LAST:event_buttonVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlAbertura;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFechamento;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPagamento;
    private javax.swing.JLabel jlPago;
    private javax.swing.JLabel jlRestante;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JTextArea taProdutos;
    private javax.swing.JTextArea taServicos;
    // End of variables declaration//GEN-END:variables
}
