/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PecaController;
import helpers.Helper;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rmb
 */
public class TelaEditarPeca extends javax.swing.JFrame {
    private String antigoNome;
    /**
     * Creates new form TelaCadastroPeca
     * @param nome
     * @param quantidade
     * @param custo
     * @param valor
     * @param prateleira
     * @param local
     */
    public TelaEditarPeca(String nome, String quantidade, String custo, String valor, String prateleira, String local) {
        initComponents();
        antigoNome = nome;
        tfNome.setText(nome);
        tfQuantidade.setText(quantidade);
        tfPreco.setText(custo);
        tfVenda.setText(valor);
        tfPrateleira.setText(prateleira);
        tfLocal.setText(local);
        tfPercentual.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfQuantidade = new javax.swing.JTextField();
        tfPreco = new javax.swing.JTextField();
        tfPrateleira = new javax.swing.JTextField();
        tfLocal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfVenda = new javax.swing.JTextField();
        tfPercentual = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGO - Cadastro Peça");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel2.setText("Quantidade");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel3.setText("Preço de custo");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel4.setText("Prateleira");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel5.setText("Local");

        tfLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLocalActionPerformed(evt);
            }
        });

        jLabel8.setText("R$");

        jLabel9.setText("unidades");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel10.setText("Valor de venda");

        jLabel11.setText("R$");

        tfVenda.setOpaque(false);

        tfPercentual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPercentualActionPerformed(evt);
            }
        });
        tfPercentual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPercentualKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPercentualKeyReleased(evt);
            }
        });

        jLabel12.setText("%");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel13.setText("Percentual de lucro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(4, 4, 4)
                                .addComponent(tfVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(4, 4, 4)
                                            .addComponent(tfPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                        .addComponent(tfLocal, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfPrateleira, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)))
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfQuantidade)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPrateleira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new TelaBuscarPeca().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String nome = tfNome.getText();
        
        if(nome.equals("")) {
            JOptionPane.showMessageDialog(null, "O nome não pode ser vazio");
        }
        else {
            String quantidade = tfQuantidade.getText();
            ArrayList<String> lista = new ArrayList<String>();
            if(quantidade.equals("")){
                JOptionPane.showMessageDialog(null, "A quantidade não pode ser vazia");
            }
            else{
                boolean erro = false;
                
                char[] unidades = quantidade.toCharArray();
                
                for (int i=0; i<quantidade.length(); i++) {
                    if(quantidade.matches("[a-z]+") || quantidade.matches("[A-Z]+")) {
                        erro = true;
                    }
                }
                if(erro) {
                    JOptionPane.showMessageDialog(null, "Digite apenas números em quantidade");
                }
                
                else {
                    
                    int quantidadeConvertida = Integer.parseInt(quantidade);
                    
                    String preco = tfPreco.getText();

                    if(preco.equals("")) {
                        JOptionPane.showMessageDialog(null, "O preço não pode ser vazio");
                    }

                    else {

                        unidades = preco.toCharArray();
                        erro = false;
                        int tamanho = preco.length();
                        preco = "";
                        
                        for (int i=0; i<tamanho; i++) {
                            if(unidades[i] == ',') {
                                preco = preco + ".";
                            }
                            
                            else {
                                preco = preco + unidades[i];
                            }
                        }
                        
                        if(preco.matches("[a-z]*") || preco.matches("[A-Z]*")) {
                            erro = true;
                        }

                        
                        if(erro) {
                            JOptionPane.showMessageDialog(null, "Digite apenas números em preço (ex: 99,99)");
                        }
                        
                        else{
                            String porcentagem = tfPercentual.getText();
                            
                            
                            if(porcentagem.matches("[A-Z]+") || porcentagem.matches("[a-z]+")) {
                                JOptionPane.showMessageDialog(null, "Digite apenas números no percentual de lucro");
                            }
                            else {
                                float precoCusto = Float.parseFloat(preco);
                                float precoVenda = Float.parseFloat(tfVenda.getText());
                                String prateleira = tfPrateleira.getText();
                                String local = tfLocal.getText();
                                String data = Helper.gerarData();

                                try {
                                    PecaController controller = new PecaController();
                                    if(controller.editarPeca(antigoNome, nome, quantidadeConvertida, precoCusto, precoVenda, data, prateleira, local)){
                                        JOptionPane.showMessageDialog(null, "Peça atualizada com sucesso!");
                                        dispose();
                                        new TelaBuscarPeca().setVisible(true);
                                    }
                                    else {
                                        JOptionPane.showMessageDialog(null, "Erro ao editar peça!");
                                        dispose();
                                        new TelaBuscarPeca().setVisible(true);
                                    }
                                } catch (IOException ex) {
                                    Logger.getLogger(TelaEditarPeca.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (ClassNotFoundException ex) {
                                    Logger.getLogger(TelaEditarPeca.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                            
                        }
                    }
                }
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfPercentualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPercentualKeyPressed
        char[] dados = tfPercentual.getText().toCharArray();
        String percentual = "";
        for (int i=0; i<dados.length; i++) {
            if(dados[i] == ',') {
                percentual = percentual + ".";
            }
            else {
                percentual = percentual + dados[i];
            }
        }
        String c = tfPreco.getText();
        if(c != ""){
            float custo = Float.parseFloat(tfPreco.getText());
            float porcentagem;
            float valorVenda = custo;
            if(percentual.equals("")){
                porcentagem = 1;
            }
            else{
                porcentagem = 1 + (Float.parseFloat(percentual)/100);
            }
            valorVenda = custo * porcentagem;

            String result = String.format("%.2f", valorVenda);
            tfVenda.setText(result);
        }
        
    }//GEN-LAST:event_tfPercentualKeyPressed

    private void tfPercentualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPercentualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPercentualActionPerformed

    private void tfPercentualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPercentualKeyReleased

        char[] dados = tfPercentual.getText().toCharArray();
        String percentual = "";
        for (int i=0; i<dados.length; i++) {
            if(dados[i] == ',') {
                percentual = percentual + ".";
            }
            else {
                percentual = percentual + dados[i];
            }
        }
        String c = tfPreco.getText();
        if(c != ""){
            float custo = Float.parseFloat(c);
            float porcentagem;
            float valorVenda = custo;
            if(percentual.equals("")){
                porcentagem = 1;
            }
            else{
                porcentagem = 1 + (Float.parseFloat(percentual)/100);
            }
            valorVenda = custo * porcentagem;

            String result = String.format("%.2f", valorVenda);
            tfVenda.setText(result);
        }

    }//GEN-LAST:event_tfPercentualKeyReleased

    private void tfLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLocalActionPerformed
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField tfLocal;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPercentual;
    private javax.swing.JTextField tfPrateleira;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfVenda;
    // End of variables declaration//GEN-END:variables
}
