/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CadernetaController;
import controller.VendaController;
import helpers.Helper;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Caderneta;
import models.Venda;

/**
 *
 * @author rmb
 */
public class TelaRelatorioMensal extends javax.swing.JFrame {

    /**
     * Creates new form TelaRelatorioMensal
     */
    private final DefaultTableModel tabelaMes;
    private final DefaultTableModel tabelaCaderneta;
    private ArrayList<Venda> vendas;
    private VendaController vendaController;
    private ArrayList<Caderneta> cadernetas;
    CadernetaController cadernetaController;
    public TelaRelatorioMensal() {
        initComponents();
        tabelaMes = (DefaultTableModel) jtMes.getModel();
        tabelaCaderneta = (DefaultTableModel) jtCaderneta.getModel(); 
        
        try {
            vendaController = new VendaController();
            cadernetaController = new CadernetaController();
            cadernetas = cadernetaController.getCadernetas();
        } catch (IOException ex) {
            Logger.getLogger(TelaRelatorioMensal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaRelatorioMensal.class.getName()).log(Level.SEVERE, null, ex);
        }
        String data = Helper.gerarDataSimples();
        char[] mes = data.toCharArray();
        data = Character.toString(mes[3]) + Character.toString(mes[4]) + "/" + Character.toString(mes[6]) + Character.toString(mes[7])
                +Character.toString(mes[8]) + Character.toString(mes[9]); 
        
        contabilizarMes(data);
    }
    
    private void contabilizarMes(String data) {
        vendas = vendaController.getVendasMes(data);
        
        char[] dia;
        String diaMes;
        ArrayList<String> passados = new ArrayList<String>();
        passados.add("");
        
        if(vendas != null){
            for(Venda venda : vendas) {
                dia = venda.getData().toCharArray();
                diaMes = Character.toString(dia[0]) + Character.toString(dia[1]);
                if(!passados.contains(diaMes)){
                    Object[] dados = {diaMes, vendaController.getNumeroProdutosDia(diaMes + "/" + data), vendaController.getNumeroServicosDia(diaMes + "/" + data),
                    String.format("%.2f", vendaController.getValorDia(diaMes + "/" + data))};
                    tabelaMes.addRow(dados);
                    passados.add(diaMes);
                }
            }
        }
        passados = new ArrayList<String>();
        ArrayList<String> datasPagamento = new ArrayList<String>();
        if(cadernetas != null){
            for(Caderneta caderneta : cadernetas) {
                datasPagamento = caderneta.getTodasDataPagamentos();
                for(String s : datasPagamento){
                    dia = s.toCharArray();
                    diaMes = Character.toString(dia[0]) + Character.toString(dia[1]);
                    if(!passados.contains(diaMes) && s.contains(data)){
                        Object[] dados = {diaMes, cadernetaController.getValorDia(diaMes + "/" + data)};
                        tabelaCaderneta.addRow(dados);
                        passados.add(diaMes);
                    }
                }
            }
        }
        
        
        gerarTotal();
    }
    
    private void gerarTotal(){
        int tamanho = tabelaMes.getRowCount();
        float total = 0;
        if(tamanho > 0){
            for (int i=0; i<tamanho; i++){
                total = total + Float.parseFloat(tabelaMes.getValueAt(i, 3).toString().replace(",", "."));
            }
        }
        
        tamanho = tabelaCaderneta.getRowCount();
        if(tamanho > 0){
            for (int i=0; i<tamanho; i++){
                total = total + Float.parseFloat(tabelaCaderneta.getValueAt(i, 1).toString().replace(",", "."));
            }
        }
        jlTotal.setText(String.format("%.2f", total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tfData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMes = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtCaderneta = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGO - Relatório Mensal");
        setResizable(false);

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data");

        buttonBuscar.setBackground(new java.awt.Color(0, 204, 204));
        buttonBuscar.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total R$: ");

        jlTotal.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jlTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlTotal.setText("0");

        jtMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Qtd produtos", "Qtd serviços", "Valor (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtMes);

        jtCaderneta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtCaderneta.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jtCaderneta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Valor (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCaderneta.setGridColor(new java.awt.Color(165, 224, 220));
        jtCaderneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCadernetaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtCaderneta);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tabela Vendas");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tabela Recebimento");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(637, 637, 637)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jlTotal))
                    .addComponent(jLabel2)))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonBuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTotal)
                    .addComponent(jLabel2)))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        
        String data = tfData.getText();
        if(!data.equals("")){
            if(data.matches("[0-9][0-9][/][0-9][0-9][0-9][0-9]")) {
                for(int i=0; i<tabelaMes.getRowCount(); i++){
                    tabelaMes.removeRow(0);
                }
                for(int i=0; i<tabelaCaderneta.getRowCount(); i++){
                    tabelaCaderneta.removeRow(0);
                }
                contabilizarMes(data);
            }
            else{
                JOptionPane.showMessageDialog(null, "Digite o mês e ano no formato MM/AAAA. Ex:(01/2020 equivale a janeiro de 2020)");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Digite o mês e ano que deseja buscar. Ex:(01/2020 equivale a janeiro de 2020)");
        }

    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
        new MenuCaixaView().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtCadernetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCadernetaMouseClicked

        jtMes.getSelectionModel().clearSelection();

    }//GEN-LAST:event_jtCadernetaMouseClicked

    private void jtMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMesMouseClicked

        jtCaderneta.getSelectionModel().clearSelection();

    }//GEN-LAST:event_jtMesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorioMensal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JTable jtCaderneta;
    private javax.swing.JTable jtMes;
    private javax.swing.JTextField tfData;
    // End of variables declaration//GEN-END:variables
}
