/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import models.Peca;

/**
 *
 * @author rmb
 */
public class TelaDetalhesProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaDetalhesProduto
     */
    public TelaDetalhesProduto(Peca peca, String data, int quantidade) {
        initComponents();
        
        jlProduto.setText(peca.getNome());
        jlQuantidade.setText("" + quantidade);
        jlCusto.setText(String.format("%.2f", peca.getPrecoCusto()));
        jlVenda.setText(String.format("%.2f", peca.getPrecoVenda()));
        jlData.setText(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlProduto = new javax.swing.JLabel();
        jlQ = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlCusto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlVenda = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGO - Detalhes Produto");
        setMinimumSize(new java.awt.Dimension(510, 344));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Produto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 71, 65, 18);

        jlProduto.setForeground(new java.awt.Color(255, 255, 255));
        jlProduto.setText("produto");
        getContentPane().add(jlProduto);
        jlProduto.setBounds(10, 97, 260, 18);

        jlQ.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jlQ.setForeground(new java.awt.Color(255, 255, 255));
        jlQ.setText("Quantidade");
        getContentPane().add(jlQ);
        jlQ.setBounds(279, 71, 94, 18);

        jlQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        jlQuantidade.setText("quantidade");
        getContentPane().add(jlQuantidade);
        jlQuantidade.setBounds(279, 97, 79, 18);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preço de custo (R$)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 189, 200, 18);

        jlCusto.setForeground(new java.awt.Color(255, 255, 255));
        jlCusto.setText("custo");
        getContentPane().add(jlCusto);
        jlCusto.setBounds(10, 215, 39, 18);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Preço de venda (R$)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(279, 189, 200, 18);

        jlVenda.setForeground(new java.awt.Color(255, 255, 255));
        jlVenda.setText("venda");
        getContentPane().add(jlVenda);
        jlVenda.setBounds(279, 215, 42, 18);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 294, 39, 18);

        buttonVoltar.setBackground(new java.awt.Color(199, 199, 199));
        buttonVoltar.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonVoltar);
        buttonVoltar.setBounds(10, 11, 100, 30);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(509, 344));
        jPanel1.setPreferredSize(new java.awt.Dimension(509, 344));

        jlData.setForeground(new java.awt.Color(255, 255, 255));
        jlData.setText("data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jlData)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(jlData)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 509, 344);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed

        dispose();

    }//GEN-LAST:event_buttonVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlCusto;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlProduto;
    private javax.swing.JLabel jlQ;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlVenda;
    // End of variables declaration//GEN-END:variables
}
